### ISSUE TITLE
Provide custom dashboards for defined users

### ISSUE THREAD

**Issue by mkayontour** [mkayontour/ansible-icingaweb2#4]
Manage Dashboards for users with custom snippets. 

```
managed_dashboards:
  - name: mkay
    dashboards:
       - default
       - windows/problems
       - windows/applikations
       - linux-generic
```
